version: '3.8'

services:
  vue:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8080:8080
    restart: always
    tty: true
    volumes:
      - ./frontend/app:/app

  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./backend/app:/app